-- Fix Turkey region/district display names after AI imports.
-- Keeps slugs/URLs stable; updates Turkish display names and location page titles.
BEGIN;

CREATE TEMP TABLE _tr_region_names (slug TEXT PRIMARY KEY, name TEXT NOT NULL) ON COMMIT DROP;
INSERT INTO _tr_region_names (slug, name) VALUES
  ('adana', 'Adana'),
  ('adiyaman', 'Adıyaman'),
  ('afyonkarahisar', 'Afyonkarahisar'),
  ('agri', 'Ağrı'),
  ('aksaray', 'Aksaray'),
  ('amasya', 'Amasya'),
  ('ankara', 'Ankara'),
  ('antalya', 'Antalya'),
  ('ardahan', 'Ardahan'),
  ('artvin', 'Artvin'),
  ('aydin', 'Aydın'),
  ('balikesir', 'Balıkesir'),
  ('bartin', 'Bartın'),
  ('batman', 'Batman'),
  ('bayburt', 'Bayburt'),
  ('bilecik', 'Bilecik'),
  ('bingol', 'Bingöl'),
  ('bitlis', 'Bitlis'),
  ('bolu', 'Bolu'),
  ('burdur', 'Burdur'),
  ('bursa', 'Bursa'),
  ('canakkale', 'Çanakkale'),
  ('cankiri', 'Çankırı'),
  ('corum', 'Çorum'),
  ('denizli', 'Denizli'),
  ('diyarbakir', 'Diyarbakır'),
  ('duzce', 'Düzce'),
  ('edirne', 'Edirne'),
  ('elazig', 'Elazığ'),
  ('erzincan', 'Erzincan'),
  ('erzurum', 'Erzurum'),
  ('eskisehir', 'Eskişehir'),
  ('gaziantep', 'Gaziantep'),
  ('giresun', 'Giresun'),
  ('gumushane', 'Gümüşhane'),
  ('hakkari', 'Hakkari'),
  ('hatay', 'Hatay'),
  ('igdir', 'Iğdır'),
  ('isparta', 'Isparta'),
  ('istanbul', 'İstanbul'),
  ('izmir', 'İzmir'),
  ('kahramanmaras', 'Kahramanmaraş'),
  ('karabuk', 'Karabük'),
  ('karaman', 'Karaman'),
  ('kars', 'Kars'),
  ('kastamonu', 'Kastamonu'),
  ('kayseri', 'Kayseri'),
  ('kilis', 'Kilis'),
  ('kirikkale', 'Kırıkkale'),
  ('kirklareli', 'Kırklareli'),
  ('kirsehir', 'Kırşehir'),
  ('kocaeli', 'Kocaeli'),
  ('konya', 'Konya'),
  ('kutahya', 'Kütahya'),
  ('malatya', 'Malatya'),
  ('manisa', 'Manisa'),
  ('mardin', 'Mardin'),
  ('mersin', 'Mersin'),
  ('mugla', 'Muğla'),
  ('mus', 'Muş'),
  ('nevsehir', 'Nevşehir'),
  ('nigde', 'Niğde'),
  ('ordu', 'Ordu'),
  ('osmaniye', 'Osmaniye'),
  ('rize', 'Rize'),
  ('sakarya', 'Sakarya'),
  ('samsun', 'Samsun'),
  ('sanliurfa', 'Şanlıurfa'),
  ('siirt', 'Siirt'),
  ('sinop', 'Sinop'),
  ('sirnak', 'Şırnak'),
  ('sivas', 'Sivas'),
  ('tekirdag', 'Tekirdağ'),
  ('tokat', 'Tokat'),
  ('trabzon', 'Trabzon'),
  ('tunceli', 'Tunceli'),
  ('usak', 'Uşak'),
  ('van', 'Van'),
  ('yalova', 'Yalova'),
  ('yozgat', 'Yozgat'),
  ('zonguldak', 'Zonguldak');

CREATE TEMP TABLE _tr_district_names (region_slug TEXT NOT NULL, slug TEXT NOT NULL, name TEXT NOT NULL, PRIMARY KEY (region_slug, slug)) ON COMMIT DROP;
INSERT INTO _tr_district_names (region_slug, slug, name) VALUES
  ('adana', 'aladag', 'Aladağ'),
  ('adana', 'ceyhan', 'Ceyhan'),
  ('adana', 'cukurova', 'Çukurova'),
  ('adana', 'feke', 'Feke'),
  ('adana', 'imamoglu', 'İmamoğlu'),
  ('adana', 'karaisali', 'Karaisalı'),
  ('adana', 'karatas', 'Karataş'),
  ('adana', 'kozan', 'Kozan'),
  ('adana', 'pozanti', 'Pozantı'),
  ('adana', 'saimbeyli', 'Saimbeyli'),
  ('adana', 'saricam', 'Sarıçam'),
  ('adana', 'seyhan', 'Seyhan'),
  ('adana', 'tufanbeyli', 'Tufanbeyli'),
  ('adana', 'yumurtalik', 'Yumurtalık'),
  ('adiyaman', 'merkez', 'Merkez'),
  ('adiyaman', 'besni', 'Besni'),
  ('adiyaman', 'celikhan', 'Çelikhan'),
  ('adiyaman', 'gerger', 'Gerger'),
  ('adiyaman', 'golbasi', 'Gölbaşı'),
  ('adiyaman', 'kahta', 'Kahta'),
  ('adiyaman', 'samsat', 'Samsat'),
  ('adiyaman', 'sincik', 'Sincik'),
  ('adiyaman', 'tut', 'Tut'),
  ('afyonkarahisar', 'merkez', 'Merkez'),
  ('afyonkarahisar', 'basmakci', 'Başmakçı'),
  ('afyonkarahisar', 'bayat', 'Bayat'),
  ('afyonkarahisar', 'bolvadin', 'Bolvadin'),
  ('afyonkarahisar', 'cay', 'Çay'),
  ('afyonkarahisar', 'cobanlar', 'Çobanlar'),
  ('afyonkarahisar', 'dazkiri', 'Dazkırı'),
  ('afyonkarahisar', 'dinar', 'Dinar'),
  ('afyonkarahisar', 'emirdag', 'Emirdağ'),
  ('afyonkarahisar', 'evciler', 'Evciler'),
  ('afyonkarahisar', 'hocalar', 'Hocalar'),
  ('afyonkarahisar', 'ihsaniye', 'İhsaniye'),
  ('afyonkarahisar', 'iscehisar', 'İscehisar'),
  ('afyonkarahisar', 'kiziloren', 'Kızılören'),
  ('afyonkarahisar', 'sandikli', 'Sandıklı'),
  ('afyonkarahisar', 'sinanpasa', 'Sinanpaşa'),
  ('afyonkarahisar', 'sultandagi', 'Sultandağı'),
  ('afyonkarahisar', 'suhut', 'Şuhut'),
  ('agri', 'merkez', 'Merkez'),
  ('agri', 'diyadin', 'Diyadin'),
  ('agri', 'dogubayazit', 'Doğubayazıt'),
  ('agri', 'eleskirt', 'Eleşkirt'),
  ('agri', 'hamur', 'Hamur'),
  ('agri', 'patnos', 'Patnos'),
  ('agri', 'taslicay', 'Taşlıçay'),
  ('agri', 'tutak', 'Tutak'),
  ('aksaray', 'merkez', 'Merkez'),
  ('aksaray', 'agacoren', 'Ağaçören'),
  ('aksaray', 'eskil', 'Eskil'),
  ('aksaray', 'gulagac', 'Gülağaç'),
  ('aksaray', 'guzelyurt', 'Güzelyurt'),
  ('aksaray', 'ortakoy', 'Ortaköy'),
  ('aksaray', 'sariyahsi', 'Sarıyahşi'),
  ('aksaray', 'sultanhani', 'Sultanhanı'),
  ('amasya', 'merkez', 'Merkez'),
  ('amasya', 'goynucek', 'Göynücek'),
  ('amasya', 'gumushacikoy', 'Gümüşhacıköy'),
  ('amasya', 'hamamozu', 'Hamamözü'),
  ('amasya', 'merzifon', 'Merzifon'),
  ('amasya', 'suluova', 'Suluova'),
  ('amasya', 'tasova', 'Taşova'),
  ('ankara', 'altindag', 'Altındağ'),
  ('ankara', 'ayas', 'Ayaş'),
  ('ankara', 'bala', 'Bala'),
  ('ankara', 'beypazari', 'Beypazarı'),
  ('ankara', 'camlidere', 'Çamlıdere'),
  ('ankara', 'cankaya', 'Çankaya'),
  ('ankara', 'cubuk', 'Çubuk'),
  ('ankara', 'elmadag', 'Elmadağ'),
  ('ankara', 'etimesgut', 'Etimesgut'),
  ('ankara', 'evren', 'Evren'),
  ('ankara', 'golbasi', 'Gölbaşı'),
  ('ankara', 'gudul', 'Güdül'),
  ('ankara', 'haymana', 'Haymana'),
  ('ankara', 'kahramankazan', 'Kahramankazan'),
  ('ankara', 'kalecik', 'Kalecik'),
  ('ankara', 'kecioren', 'Keçiören'),
  ('ankara', 'kizilcahamam', 'Kızılcahamam'),
  ('ankara', 'mamak', 'Mamak'),
  ('ankara', 'nallihan', 'Nallıhan'),
  ('ankara', 'polatli', 'Polatlı'),
  ('ankara', 'pursaklar', 'Pursaklar'),
  ('ankara', 'sincan', 'Sincan'),
  ('ankara', 'sereflikochisan', 'Şereflikoçhisar'),
  ('ankara', 'yenimahalle', 'Yenimahalle'),
  ('ankara', 'akyurt', 'Akyurt'),
  ('antalya', 'akseki', 'Akseki'),
  ('antalya', 'aksu', 'Aksu'),
  ('antalya', 'alanya', 'Alanya'),
  ('antalya', 'demre', 'Demre'),
  ('antalya', 'dosemealti', 'Döşemealtı'),
  ('antalya', 'elmali', 'Elmalı'),
  ('antalya', 'finike', 'Finike'),
  ('antalya', 'gazipasa', 'Gazipaşa'),
  ('antalya', 'gundogmus', 'Gündoğmuş'),
  ('antalya', 'ibradi', 'İbradı'),
  ('antalya', 'kas', 'Kaş'),
  ('antalya', 'kemer', 'Kemer'),
  ('antalya', 'kepez', 'Kepez'),
  ('antalya', 'konyaalti', 'Konyaaltı'),
  ('antalya', 'korkuteli', 'Korkuteli'),
  ('antalya', 'kumluca', 'Kumluca'),
  ('antalya', 'manavgat', 'Manavgat'),
  ('antalya', 'muratpasa', 'Muratpaşa'),
  ('antalya', 'serik', 'Serik'),
  ('ardahan', 'merkez', 'Merkez'),
  ('ardahan', 'cildir', 'Çıldır'),
  ('ardahan', 'damal', 'Damal'),
  ('ardahan', 'gole', 'Göle'),
  ('ardahan', 'hanak', 'Hanak'),
  ('ardahan', 'posof', 'Posof'),
  ('artvin', 'merkez', 'Merkez'),
  ('artvin', 'ardanuc', 'Ardanuç'),
  ('artvin', 'arhavi', 'Arhavi'),
  ('artvin', 'borcka', 'Borçka'),
  ('artvin', 'hopa', 'Hopa'),
  ('artvin', 'murgul', 'Murgul'),
  ('artvin', 'savsat', 'Şavşat'),
  ('artvin', 'yusufeli', 'Yusufeli'),
  ('aydin', 'efeler', 'Efeler'),
  ('aydin', 'bozdogan', 'Bozdoğan'),
  ('aydin', 'buharkent', 'Buharkent'),
  ('aydin', 'cine', 'Çine'),
  ('aydin', 'didim', 'Didim'),
  ('aydin', 'germencik', 'Germencik'),
  ('aydin', 'incirliova', 'İncirliova'),
  ('aydin', 'karacasu', 'Karacasu'),
  ('aydin', 'karpuzlu', 'Karpuzlu'),
  ('aydin', 'kocarli', 'Koçarlı'),
  ('aydin', 'kosk', 'Köşk'),
  ('aydin', 'kusadasi', 'Kuşadası'),
  ('aydin', 'kuyucak', 'Kuyucak'),
  ('aydin', 'nazilli', 'Nazilli'),
  ('aydin', 'soke', 'Söke'),
  ('aydin', 'sultanhisar', 'Sultanhisar'),
  ('aydin', 'yenipazar', 'Yenipazar'),
  ('balikesir', 'altieylul', 'Altıeylül'),
  ('balikesir', 'ayvalik', 'Ayvalık'),
  ('balikesir', 'balya', 'Balya'),
  ('balikesir', 'bandirma', 'Bandırma'),
  ('balikesir', 'bigadic', 'Bigadiç'),
  ('balikesir', 'burhaniye', 'Burhaniye'),
  ('balikesir', 'dursunbey', 'Dursunbey'),
  ('balikesir', 'edremit', 'Edremit'),
  ('balikesir', 'erdek', 'Erdek'),
  ('balikesir', 'gomec', 'Gömeç'),
  ('balikesir', 'gonen', 'Gönen'),
  ('balikesir', 'havran', 'Havran'),
  ('balikesir', 'ivrindi', 'İvrindi'),
  ('balikesir', 'karesi', 'Karesi'),
  ('balikesir', 'kepsut', 'Kepsut'),
  ('balikesir', 'manyas', 'Manyas'),
  ('balikesir', 'marmara', 'Marmara'),
  ('balikesir', 'savastepe', 'Savaştepe'),
  ('balikesir', 'sindirgi', 'Sındırgı'),
  ('balikesir', 'susurluk', 'Susurluk'),
  ('bartin', 'merkez', 'Merkez'),
  ('bartin', 'amasra', 'Amasra'),
  ('bartin', 'kurucasile', 'Kurucaşile'),
  ('bartin', 'ulus', 'Ulus'),
  ('batman', 'merkez', 'Merkez'),
  ('batman', 'besiri', 'Beşiri'),
  ('batman', 'gercus', 'Gercüş'),
  ('batman', 'hasankeyf', 'Hasankeyf'),
  ('batman', 'kozluk', 'Kozluk'),
  ('batman', 'sason', 'Sason'),
  ('bayburt', 'merkez', 'Merkez'),
  ('bayburt', 'aydintepe', 'Aydıntepe'),
  ('bayburt', 'demirozu', 'Demirözü'),
  ('bilecik', 'merkez', 'Merkez'),
  ('bilecik', 'bozuyuk', 'Bozüyük'),
  ('bilecik', 'golpazari', 'Gölpazarı'),
  ('bilecik', 'inhisar', 'İnhisar'),
  ('bilecik', 'osmaneli', 'Osmaneli'),
  ('bilecik', 'pazaryeri', 'Pazaryeri'),
  ('bilecik', 'sogut', 'Söğüt'),
  ('bilecik', 'yenipazar', 'Yenipazar'),
  ('bingol', 'merkez', 'Merkez'),
  ('bingol', 'adakli', 'Adaklı'),
  ('bingol', 'genc', 'Genç'),
  ('bingol', 'karliova', 'Karlıova'),
  ('bingol', 'kigi', 'Kiğı'),
  ('bingol', 'solhan', 'Solhan'),
  ('bingol', 'yayladere', 'Yayladere'),
  ('bingol', 'yedisu', 'Yedisu'),
  ('bitlis', 'merkez', 'Merkez'),
  ('bitlis', 'adilcevaz', 'Adilcevaz'),
  ('bitlis', 'ahlat', 'Ahlat'),
  ('bitlis', 'guroymak', 'Güroymak'),
  ('bitlis', 'hizan', 'Hizan'),
  ('bitlis', 'mutki', 'Mutki'),
  ('bolu', 'merkez', 'Merkez'),
  ('bolu', 'dortdivan', 'Dörtdivan'),
  ('bolu', 'gerede', 'Gerede'),
  ('bolu', 'goynuk', 'Göynük'),
  ('bolu', 'kibriscik', 'Kıbrıscık'),
  ('bolu', 'mengen', 'Mengen'),
  ('bolu', 'mudurnu', 'Mudurnu'),
  ('bolu', 'seben', 'Seben'),
  ('burdur', 'merkez', 'Merkez'),
  ('burdur', 'aglasun', 'Ağlasun'),
  ('burdur', 'altinyayla', 'Altınyayla'),
  ('burdur', 'bucak', 'Bucak'),
  ('burdur', 'cavdir', 'Çavdır'),
  ('burdur', 'celtikci', 'Çeltikçi'),
  ('burdur', 'golhisar', 'Gölhisar'),
  ('burdur', 'karamanli', 'Karamanlı'),
  ('burdur', 'kemer', 'Kemer'),
  ('burdur', 'tefenni', 'Tefenni'),
  ('burdur', 'yesilova', 'Yeşilova'),
  ('bursa', 'buyukorhan', 'Büyükorhan'),
  ('bursa', 'gemlik', 'Gemlik'),
  ('bursa', 'gursu', 'Gürsu'),
  ('bursa', 'harmancik', 'Harmancık'),
  ('bursa', 'inegol', 'İnegöl'),
  ('bursa', 'iznik', 'İznik'),
  ('bursa', 'karacabey', 'Karacabey'),
  ('bursa', 'keles', 'Keles'),
  ('bursa', 'mudanya', 'Mudanya'),
  ('bursa', 'mustafakemalpasa', 'Mustafakemalpaşa'),
  ('bursa', 'nilufer', 'Nilüfer'),
  ('bursa', 'orhaneli', 'Orhaneli'),
  ('bursa', 'orhangazi', 'Orhangazi'),
  ('bursa', 'osmangazi', 'Osmangazi'),
  ('bursa', 'yenisehir', 'Yenişehir'),
  ('bursa', 'yildirim', 'Yıldırım'),
  ('canakkale', 'merkez', 'Merkez'),
  ('canakkale', 'ayvacik', 'Ayvacık'),
  ('canakkale', 'bayframic', 'Bayramiç'),
  ('canakkale', 'biga', 'Biga'),
  ('canakkale', 'bozcaada', 'Bozcaada'),
  ('canakkale', 'can', 'Çan'),
  ('canakkale', 'eceabat', 'Eceabat'),
  ('canakkale', 'ezine', 'Ezine'),
  ('canakkale', 'gelibolu', 'Gelibolu'),
  ('canakkale', 'gokcaada', 'Gökçeada'),
  ('canakkale', 'lapseki', 'Lapseki'),
  ('canakkale', 'yenice', 'Yenice'),
  ('cankiri', 'merkez', 'Merkez'),
  ('cankiri', 'atkaracalar', 'Atkaracalar'),
  ('cankiri', 'bayramoren', 'Bayramören'),
  ('cankiri', 'cerkes', 'Çerkeş'),
  ('cankiri', 'eldivan', 'Eldivan'),
  ('cankiri', 'ilgaz', 'Ilgaz'),
  ('cankiri', 'kizilirmak', 'Kızılırmak'),
  ('cankiri', 'korgun', 'Korgun'),
  ('cankiri', 'kursunlu', 'Kurşunlu'),
  ('cankiri', 'orta', 'Orta'),
  ('cankiri', 'sabanözu', 'Şabanözü'),
  ('cankiri', 'yaprakli', 'Yapraklı'),
  ('corum', 'merkez', 'Merkez'),
  ('corum', 'alaca', 'Alaca'),
  ('corum', 'bayat', 'Bayat'),
  ('corum', 'bogazkale', 'Boğazkale'),
  ('corum', 'dodurga', 'Dodurga'),
  ('corum', 'iskilip', 'İskilip'),
  ('corum', 'kargi', 'Kargı'),
  ('corum', 'lacin', 'Laçin'),
  ('corum', 'mecitozu', 'Mecitözü'),
  ('corum', 'oguzlar', 'Oğuzlar'),
  ('corum', 'ortakoy', 'Ortaköy'),
  ('corum', 'osmancik', 'Osmancık'),
  ('corum', 'sungurlu', 'Sungurlu'),
  ('corum', 'ugurludag', 'Uğurludağ'),
  ('denizli', 'acipayam', 'Acıpayam'),
  ('denizli', 'babadag', 'Babadağ'),
  ('denizli', 'baklan', 'Baklan'),
  ('denizli', 'bekilli', 'Bekilli'),
  ('denizli', 'beyagac', 'Beyağaç'),
  ('denizli', 'bozkurt', 'Bozkurt'),
  ('denizli', 'buldan', 'Buldan'),
  ('denizli', 'cal', 'Çal'),
  ('denizli', 'cameli', 'Çameli'),
  ('denizli', 'cardak', 'Çardak'),
  ('denizli', 'civril', 'Çivril'),
  ('denizli', 'guney', 'Güney'),
  ('denizli', 'honaz', 'Honaz'),
  ('denizli', 'kale', 'Kale'),
  ('denizli', 'merkezefendi', 'Merkezefendi'),
  ('denizli', 'pamukkale', 'Pamukkale'),
  ('denizli', 'saraykoy', 'Sarayköy'),
  ('denizli', 'serinhisar', 'Serinhisar'),
  ('denizli', 'tavas', 'Tavas'),
  ('diyarbakir', 'baglar', 'Bağlar'),
  ('diyarbakir', 'bismil', 'Bismil'),
  ('diyarbakir', 'cermik', 'Çermik'),
  ('diyarbakir', 'cinar', 'Çınar'),
  ('diyarbakir', 'cungus', 'Çüngüş'),
  ('diyarbakir', 'dicle', 'Dicle'),
  ('diyarbakir', 'egil', 'Eğil'),
  ('diyarbakir', 'ergani', 'Ergani'),
  ('diyarbakir', 'hani', 'Hani'),
  ('diyarbakir', 'hazro', 'Hazro'),
  ('diyarbakir', 'kayapinar', 'Kayapınar'),
  ('diyarbakir', 'kocakoy', 'Kocaköy'),
  ('diyarbakir', 'kulp', 'Kulp'),
  ('diyarbakir', 'lice', 'Lice'),
  ('diyarbakir', 'silvan', 'Silvan'),
  ('diyarbakir', 'sur', 'Sur'),
  ('diyarbakir', 'yenisehir', 'Yenişehir'),
  ('duzce', 'merkez', 'Merkez'),
  ('duzce', 'akcakoca', 'Akçakoca'),
  ('duzce', 'cumayeri', 'Cumayeri'),
  ('duzce', 'cilimli', 'Çilimli'),
  ('duzce', 'golyaka', 'Gölyaka'),
  ('duzce', 'gumusova', 'Gümüşova'),
  ('duzce', 'kaynasli', 'Kaynaşlı'),
  ('duzce', 'yigilca', 'Yığılca'),
  ('edirne', 'merkez', 'Merkez'),
  ('edirne', 'enez', 'Enez'),
  ('edirne', 'havsa', 'Havsa'),
  ('edirne', 'ipsala', 'İpsala'),
  ('edirne', 'kesan', 'Keşan'),
  ('edirne', 'lalapasa', 'Lalapaşa'),
  ('edirne', 'meric', 'Meriç'),
  ('edirne', 'suloglu', 'Süloğlu'),
  ('edirne', 'uzunkopru', 'Uzunköprü'),
  ('elazig', 'merkez', 'Merkez'),
  ('elazig', 'agin', 'Ağın'),
  ('elazig', 'alacakaya', 'Alacakaya'),
  ('elazig', 'aricak', 'Arıcak'),
  ('elazig', 'baskil', 'Baskil'),
  ('elazig', 'karakocan', 'Karakoçan'),
  ('elazig', 'keban', 'Keban'),
  ('elazig', 'kovancilar', 'Kovancılar'),
  ('elazig', 'maden', 'Maden'),
  ('elazig', 'palu', 'Palu'),
  ('elazig', 'sivrice', 'Sivrice'),
  ('erzincan', 'merkez', 'Merkez'),
  ('erzincan', 'cayirli', 'Çayırlı'),
  ('erzincan', 'ilic', 'İliç'),
  ('erzincan', 'kemah', 'Kemah'),
  ('erzincan', 'kemaliye', 'Kemaliye'),
  ('erzincan', 'otlukbeli', 'Otlukbeli'),
  ('erzincan', 'refahiye', 'Refahiye'),
  ('erzincan', 'tercan', 'Tercan'),
  ('erzincan', 'uzumlu', 'Üzümlü'),
  ('erzurum', 'aziziye', 'Aziziye'),
  ('erzurum', 'palandoken', 'Palandöken'),
  ('erzurum', 'yakutiye', 'Yakutiye'),
  ('erzurum', 'askale', 'Aşkale'),
  ('erzurum', 'cat', 'Çat'),
  ('erzurum', 'hinis', 'Hınıs'),
  ('erzurum', 'horasan', 'Horasan'),
  ('erzurum', 'ispir', 'İspir'),
  ('erzurum', 'karayazi', 'Karayazı'),
  ('erzurum', 'koprukoy', 'Köprüköy'),
  ('erzurum', 'narman', 'Narman'),
  ('erzurum', 'oltu', 'Oltu'),
  ('erzurum', 'olur', 'Olur'),
  ('erzurum', 'pazaryolu', 'Pazaryolu'),
  ('erzurum', 'senkaya', 'Şenkaya'),
  ('erzurum', 'tekman', 'Tekman'),
  ('erzurum', 'tortum', 'Tortum'),
  ('erzurum', 'uzundere', 'Uzundere'),
  ('eskisehir', 'odunpazari', 'Odunpazarı'),
  ('eskisehir', 'tepebasi', 'Tepebaşı'),
  ('eskisehir', 'alpu', 'Alpu'),
  ('eskisehir', 'beylikova', 'Beylikova'),
  ('eskisehir', 'cifteler', 'Çifteler'),
  ('eskisehir', 'gunyuzu', 'Günyüzü'),
  ('eskisehir', 'han', 'Han'),
  ('eskisehir', 'inonu', 'İnönü'),
  ('eskisehir', 'mahmudiye', 'Mahmudiye'),
  ('eskisehir', 'mihalgazi', 'Mihalgazi'),
  ('eskisehir', 'mihalliccik', 'Mihallıçcık'),
  ('eskisehir', 'saricakaya', 'Sarıcakaya'),
  ('eskisehir', 'seyitgazi', 'Seyitgazi'),
  ('eskisehir', 'sivrihisar', 'Sivrihisar'),
  ('gaziantep', 'araban', 'Araban'),
  ('gaziantep', 'islahiye', 'İslahiye'),
  ('gaziantep', 'karkamis', 'Karkamış'),
  ('gaziantep', 'nizip', 'Nizip'),
  ('gaziantep', 'nurdagi', 'Nurdağı'),
  ('gaziantep', 'oguzeli', 'Oğuzeli'),
  ('gaziantep', 'sahinbey', 'Şahinbey'),
  ('gaziantep', 'sehitkamil', 'Şehitkamil'),
  ('gaziantep', 'yavuzeli', 'Yavuzeli'),
  ('giresun', 'merkez', 'Merkez'),
  ('giresun', 'alucra', 'Alucra'),
  ('giresun', 'bulancak', 'Bulancak'),
  ('giresun', 'camoluk', 'Çamoluk'),
  ('giresun', 'canakci', 'Çanakçı'),
  ('giresun', 'dereli', 'Dereli'),
  ('giresun', 'dogankent', 'Doğankent'),
  ('giresun', 'espiye', 'Espiye'),
  ('giresun', 'eynesil', 'Eynesil'),
  ('giresun', 'gorele', 'Görele'),
  ('giresun', 'guce', 'Güce'),
  ('giresun', 'kesap', 'Keşap'),
  ('giresun', 'piraziz', 'Piraziz'),
  ('giresun', 'sebinkarahisar', 'Şebinkarahisar'),
  ('giresun', 'tirebolu', 'Tirebolu'),
  ('giresun', 'yaglidere', 'Yağlıdere'),
  ('gumushane', 'merkez', 'Merkez'),
  ('gumushane', 'kelkit', 'Kelkit'),
  ('gumushane', 'kose', 'Köse'),
  ('gumushane', 'kurtun', 'Kürtün'),
  ('gumushane', 'siran', 'Şiran'),
  ('gumushane', 'torul', 'Torul'),
  ('hakkari', 'merkez', 'Merkez'),
  ('hakkari', 'cukurca', 'Çukurca'),
  ('hakkari', 'semdinli', 'Şemdinli'),
  ('hakkari', 'yuksekova', 'Yüksekova'),
  ('hatay', 'antakya', 'Antakya'),
  ('hatay', 'arsuz', 'Arsuz'),
  ('hatay', 'belen', 'Belen'),
  ('hatay', 'defne', 'Defne'),
  ('hatay', 'dortyol', 'Dörtyol'),
  ('hatay', 'erzin', 'Erzin'),
  ('hatay', 'hassa', 'Hassa'),
  ('hatay', 'iskenderun', 'İskenderun'),
  ('hatay', 'kirikhan', 'Kırıkhan'),
  ('hatay', 'kumlu', 'Kumlu'),
  ('hatay', 'payas', 'Payas'),
  ('hatay', 'reyhanli', 'Reyhanlı'),
  ('hatay', 'samandag', 'Samandağ'),
  ('hatay', 'yayladagi', 'Yayladağı'),
  ('igdir', 'merkez', 'Merkez'),
  ('igdir', 'aralik', 'Aralık'),
  ('igdir', 'karakoyunlu', 'Karakoyunlu'),
  ('igdir', 'tuzluca', 'Tuzluca'),
  ('isparta', 'merkez', 'Merkez'),
  ('isparta', 'aksu', 'Aksu'),
  ('isparta', 'atabey', 'Atabey'),
  ('isparta', 'egirdir', 'Eğirdir'),
  ('isparta', 'gelendost', 'Gelendost'),
  ('isparta', 'gonen', 'Gönen'),
  ('isparta', 'keciborlu', 'Keçiborlu'),
  ('isparta', 'senirkent', 'Senirkent'),
  ('isparta', 'sutculer', 'Sütçüler'),
  ('isparta', 'sarkikaraagac', 'Şarkikaraağaç'),
  ('isparta', 'uluborlu', 'Uluborlu'),
  ('isparta', 'yalvac', 'Yalvaç'),
  ('isparta', 'yenisarbademli', 'Yenişarbademli'),
  ('istanbul', 'adalar', 'Adalar'),
  ('istanbul', 'arnavutkoy', 'Arnavutköy'),
  ('istanbul', 'atasehir', 'Ataşehir'),
  ('istanbul', 'avcilar', 'Avcılar'),
  ('istanbul', 'bagcilar', 'Bağcılar'),
  ('istanbul', 'bahcelievler', 'Bahçelievler'),
  ('istanbul', 'bakirkoy', 'Bakırköy'),
  ('istanbul', 'basaksehir', 'Başakşehir'),
  ('istanbul', 'bayrampasa', 'Bayrampaşa'),
  ('istanbul', 'besiktas', 'Beşiktaş'),
  ('istanbul', 'beykoz', 'Beykoz'),
  ('istanbul', 'beylikduzu', 'Beylikdüzü'),
  ('istanbul', 'beyoglu', 'Beyoğlu'),
  ('istanbul', 'buyukcekmece', 'Büyükçekmece'),
  ('istanbul', 'catalca', 'Çatalca'),
  ('istanbul', 'cekmekoy', 'Çekmeköy'),
  ('istanbul', 'esenler', 'Esenler'),
  ('istanbul', 'esenyurt', 'Esenyurt'),
  ('istanbul', 'eyupsultan', 'Eyüpsultan'),
  ('istanbul', 'fatih', 'Fatih'),
  ('istanbul', 'gaziosmanpasa', 'Gaziosmanpaşa'),
  ('istanbul', 'gungoren', 'Güngören'),
  ('istanbul', 'kadikoy', 'Kadıköy'),
  ('istanbul', 'kagithane', 'Kağıthane'),
  ('istanbul', 'kartal', 'Kartal'),
  ('istanbul', 'kucukcekmece', 'Küçükçekmece'),
  ('istanbul', 'maltepe', 'Maltepe'),
  ('istanbul', 'pendik', 'Pendik'),
  ('istanbul', 'sancaktepe', 'Sancaktepe'),
  ('istanbul', 'sariyer', 'Sarıyer'),
  ('istanbul', 'silivri', 'Silivri'),
  ('istanbul', 'sultanbeyli', 'Sultanbeyli'),
  ('istanbul', 'sultangazi', 'Sultangazi'),
  ('istanbul', 'sile', 'Şile'),
  ('istanbul', 'sisli', 'Şişli'),
  ('istanbul', 'tuzla', 'Tuzla'),
  ('istanbul', 'umraniye', 'Ümraniye'),
  ('istanbul', 'uskudar', 'Üsküdar'),
  ('istanbul', 'zeytinburnu', 'Zeytinburnu'),
  ('izmir', 'aliaga', 'Aliağa'),
  ('izmir', 'balcova', 'Balçova'),
  ('izmir', 'bayindir', 'Bayındır'),
  ('izmir', 'bayrakli', 'Bayraklı'),
  ('izmir', 'bergama', 'Bergama'),
  ('izmir', 'beydag', 'Beydağ'),
  ('izmir', 'bornova', 'Bornova'),
  ('izmir', 'buca', 'Buca'),
  ('izmir', 'cesme', 'Çeşme'),
  ('izmir', 'cigli', 'Çiğli'),
  ('izmir', 'dikili', 'Dikili'),
  ('izmir', 'foca', 'Foça'),
  ('izmir', 'gaziemir', 'Gaziemir'),
  ('izmir', 'guzelbahce', 'Güzelbahçe'),
  ('izmir', 'karabaglar', 'Karabağlar'),
  ('izmir', 'karaburun', 'Karaburun'),
  ('izmir', 'karsiyaka', 'Karşıyaka'),
  ('izmir', 'kemalpasa', 'Kemalpaşa'),
  ('izmir', 'kinik', 'Kınık'),
  ('izmir', 'kiraz', 'Kiraz'),
  ('izmir', 'konak', 'Konak'),
  ('izmir', 'menderes', 'Menderes'),
  ('izmir', 'menemen', 'Menemen'),
  ('izmir', 'narlidere', 'Narlıdere'),
  ('izmir', 'odemis', 'Ödemiş'),
  ('izmir', 'seferihisar', 'Seferihisar'),
  ('izmir', 'selcuk', 'Selçuk'),
  ('izmir', 'tire', 'Tire'),
  ('izmir', 'torbali', 'Torbalı'),
  ('izmir', 'urla', 'Urla'),
  ('kahramanmaras', 'afsin', 'Afşin'),
  ('kahramanmaras', 'andirin', 'Andırın'),
  ('kahramanmaras', 'caglayancerit', 'Çağlayancerit'),
  ('kahramanmaras', 'dulkadiroglu', 'Dulkadiroğlu'),
  ('kahramanmaras', 'ekinozu', 'Ekinözü'),
  ('kahramanmaras', 'elbistan', 'Elbistan'),
  ('kahramanmaras', 'goksun', 'Göksun'),
  ('kahramanmaras', 'nurhak', 'Nurhak'),
  ('kahramanmaras', 'onikisubat', 'Onikişubat'),
  ('kahramanmaras', 'pazarcik', 'Pazarcık'),
  ('kahramanmaras', 'turkoglu', 'Türkoğlu'),
  ('karabuk', 'merkez', 'Merkez'),
  ('karabuk', 'eflani', 'Eflani'),
  ('karabuk', 'eskipazar', 'Eskipazar'),
  ('karabuk', 'ovacik', 'Ovacık'),
  ('karabuk', 'safranbolu', 'Safranbolu'),
  ('karabuk', 'yenice', 'Yenice'),
  ('karaman', 'merkez', 'Merkez'),
  ('karaman', 'ayranci', 'Ayrancı'),
  ('karaman', 'basyayla', 'Başyayla'),
  ('karaman', 'ermenek', 'Ermenek'),
  ('karaman', 'kazimkarabekir', 'Kazımkarabekir'),
  ('karaman', 'sariveliler', 'Sarıveliler'),
  ('kars', 'merkez', 'Merkez'),
  ('kars', 'akyaka', 'Akyaka'),
  ('kars', 'arpacay', 'Arpaçay'),
  ('kars', 'digor', 'Digor'),
  ('kars', 'kagizman', 'Kağızman'),
  ('kars', 'sarikamis', 'Sarıkamış'),
  ('kars', 'selim', 'Selim'),
  ('kars', 'susuz', 'Susuz'),
  ('kastamonu', 'merkez', 'Merkez'),
  ('kastamonu', 'abana', 'Abana'),
  ('kastamonu', 'agli', 'Ağlı'),
  ('kastamonu', 'arac', 'Araç'),
  ('kastamonu', 'azdavay', 'Azdavay'),
  ('kastamonu', 'bozkurt', 'Bozkurt'),
  ('kastamonu', 'cide', 'Cide'),
  ('kastamonu', 'catalzeytin', 'Çatalzeytin'),
  ('kastamonu', 'daday', 'Daday'),
  ('kastamonu', 'devrekani', 'Devrekani'),
  ('kastamonu', 'doganyurt', 'Doğanyurt'),
  ('kastamonu', 'hanonü', 'Hanönü'),
  ('kastamonu', 'ihsangazi', 'İhsangazi'),
  ('kastamonu', 'inebolu', 'İnebolu'),
  ('kastamonu', 'kure', 'Küre'),
  ('kastamonu', 'pinarbasi', 'Pınarbaşı'),
  ('kastamonu', 'seydiler', 'Seydiler'),
  ('kastamonu', 'senpazar', 'Şenpazar'),
  ('kastamonu', 'taskopru', 'Taşköprü'),
  ('kastamonu', 'tosya', 'Tosya'),
  ('kayseri', 'akkisla', 'Akkışla'),
  ('kayseri', 'bunyan', 'Bünyan'),
  ('kayseri', 'develi', 'Develi'),
  ('kayseri', 'felahiye', 'Felahiye'),
  ('kayseri', 'hacilar', 'Hacılar'),
  ('kayseri', 'incesu', 'İncesu'),
  ('kayseri', 'kocasinan', 'Kocasinan'),
  ('kayseri', 'melikgazi', 'Melikgazi'),
  ('kayseri', 'ozvatan', 'Özvatan'),
  ('kayseri', 'pinarbasi', 'Pınarbaşı'),
  ('kayseri', 'sarioglan', 'Sarıoğlan'),
  ('kayseri', 'sariz', 'Sarız'),
  ('kayseri', 'talas', 'Talas'),
  ('kayseri', 'tomarza', 'Tomarza'),
  ('kayseri', 'yahyali', 'Yahyalı'),
  ('kayseri', 'yesilhisar', 'Yeşilhisar'),
  ('kilis', 'merkez', 'Merkez'),
  ('kilis', 'elbeyli', 'Elbeyli'),
  ('kilis', 'musabeyli', 'Musabeyli'),
  ('kilis', 'polateli', 'Polateli'),
  ('kirikkale', 'merkez', 'Merkez'),
  ('kirikkale', 'bahsili', 'Bahşılı'),
  ('kirikkale', 'baliseyh', 'Balışeyh'),
  ('kirikkale', 'celebi', 'Çelebi'),
  ('kirikkale', 'delice', 'Delice'),
  ('kirikkale', 'karakecili', 'Karakeçili'),
  ('kirikkale', 'keskin', 'Keskin'),
  ('kirikkale', 'sulakyurt', 'Sulakyurt'),
  ('kirikkale', 'yahsihan', 'Yahşihan'),
  ('kirklareli', 'merkez', 'Merkez'),
  ('kirklareli', 'babaeski', 'Babaeski'),
  ('kirklareli', 'demirkoy', 'Demirköy'),
  ('kirklareli', 'kofcaz', 'Kofçaz'),
  ('kirklareli', 'luleburgaz', 'Lüleburgaz'),
  ('kirklareli', 'pehlivankoy', 'Pehlivanköy'),
  ('kirklareli', 'pinarhisar', 'Pınarhisar'),
  ('kirklareli', 'vize', 'Vize'),
  ('kirsehir', 'merkez', 'Merkez'),
  ('kirsehir', 'akcakent', 'Akçakent'),
  ('kirsehir', 'akpinar', 'Akpınar'),
  ('kirsehir', 'boztepe', 'Boztepe'),
  ('kirsehir', 'cicekdagi', 'Çiçekdağı'),
  ('kirsehir', 'kaman', 'Kaman'),
  ('kirsehir', 'mucur', 'Mucur'),
  ('kocaeli', 'basiskele', 'Başiskele'),
  ('kocaeli', 'cayirova', 'Çayırova'),
  ('kocaeli', 'darica', 'Darıca'),
  ('kocaeli', 'derince', 'Derince'),
  ('kocaeli', 'dilovasi', 'Dilovası'),
  ('kocaeli', 'gebze', 'Gebze'),
  ('kocaeli', 'golcuk', 'Gölcük'),
  ('kocaeli', 'izmit', 'İzmit'),
  ('kocaeli', 'kandira', 'Kandıra'),
  ('kocaeli', 'karamursel', 'Karamürsel'),
  ('kocaeli', 'kartepe', 'Kartepe'),
  ('kocaeli', 'korfez', 'Körfez'),
  ('konya', 'ahirli', 'Ahırlı'),
  ('konya', 'akoren', 'Akören'),
  ('konya', 'aksehir', 'Akşehir'),
  ('konya', 'altinekin', 'Altınekin'),
  ('konya', 'beysehir', 'Beyşehir'),
  ('konya', 'bozkir', 'Bozkır'),
  ('konya', 'cihanbeyli', 'Cihanbeyli'),
  ('konya', 'celtik', 'Çeltik'),
  ('konya', 'cumra', 'Çumra'),
  ('konya', 'derbent', 'Derbent'),
  ('konya', 'derebucak', 'Derebucak'),
  ('konya', 'doganhisar', 'Doğanhisar'),
  ('konya', 'emirgazi', 'Emirgazi'),
  ('konya', 'eregli', 'Ereğli'),
  ('konya', 'guneysinir', 'Güneysinir'),
  ('konya', 'hadim', 'Hadim'),
  ('konya', 'halkapinar', 'Halkapınar'),
  ('konya', 'huyuk', 'Hüyük'),
  ('konya', 'ilgin', 'Ilgın'),
  ('konya', 'kadinhani', 'Kadınhanı'),
  ('konya', 'karapinar', 'Karapınar'),
  ('konya', 'karatay', 'Karatay'),
  ('konya', 'kulu', 'Kulu'),
  ('konya', 'meram', 'Meram'),
  ('konya', 'sarayonu', 'Sarayönü'),
  ('konya', 'selcuklu', 'Selçuklu'),
  ('konya', 'seydisehir', 'Seydişehir'),
  ('konya', 'taskent', 'Taşkent'),
  ('konya', 'tuzlukcu', 'Tuzlukçu'),
  ('konya', 'yalihuyuk', 'Yalıhüyük'),
  ('konya', 'yunak', 'Yunak'),
  ('kutahya', 'merkez', 'Merkez'),
  ('kutahya', 'altintas', 'Altıntaş'),
  ('kutahya', 'aslanapa', 'Aslanapa'),
  ('kutahya', 'cavdarhisar', 'Çavdarhisar'),
  ('kutahya', 'domanic', 'Domaniç'),
  ('kutahya', 'dumlupinar', 'Dumlupınar'),
  ('kutahya', 'emet', 'Emet'),
  ('kutahya', 'gediz', 'Gediz'),
  ('kutahya', 'hisarcik', 'Hisarcık'),
  ('kutahya', 'pazarlar', 'Pazarlar'),
  ('kutahya', 'simav', 'Simav'),
  ('kutahya', 'saphane', 'Şaphane'),
  ('kutahya', 'tavsanli', 'Tavşanlı'),
  ('malatya', 'akcadag', 'Akçadağ'),
  ('malatya', 'arapgir', 'Arapgir'),
  ('malatya', 'arguvan', 'Arguvan'),
  ('malatya', 'battalgazi', 'Battalgazi'),
  ('malatya', 'darende', 'Darende'),
  ('malatya', 'dogansehir', 'Doğanşehir'),
  ('malatya', 'doganyol', 'Doğanyol'),
  ('malatya', 'hekimhan', 'Hekimhan'),
  ('malatya', 'kale', 'Kale'),
  ('malatya', 'kuluncak', 'Kuluncak'),
  ('malatya', 'puturge', 'Pütürge'),
  ('malatya', 'yazihan', 'Yazıhan'),
  ('malatya', 'yesilyurt', 'Yeşilyurt'),
  ('manisa', 'ahmetli', 'Ahmetli'),
  ('manisa', 'akhisar', 'Akhisar'),
  ('manisa', 'alasehir', 'Alaşehir'),
  ('manisa', 'demirci', 'Demirci'),
  ('manisa', 'golmarmara', 'Gölmarmara'),
  ('manisa', 'gordes', 'Gördes'),
  ('manisa', 'kirkagac', 'Kırkağaç'),
  ('manisa', 'koprubasi', 'Köprübaşı'),
  ('manisa', 'kula', 'Kula'),
  ('manisa', 'salihli', 'Salihli'),
  ('manisa', 'sarigol', 'Sarıgöl'),
  ('manisa', 'saruhanli', 'Saruhanlı'),
  ('manisa', 'selendi', 'Selendi'),
  ('manisa', 'soma', 'Soma'),
  ('manisa', 'sehzadeler', 'Şehzadeler'),
  ('manisa', 'turgutlu', 'Turgutlu'),
  ('manisa', 'yunusemre', 'Yunusemre'),
  ('mardin', 'artuklu', 'Artuklu'),
  ('mardin', 'dargecit', 'Dargeçit'),
  ('mardin', 'derik', 'Derik'),
  ('mardin', 'kiziltepe', 'Kızıltepe'),
  ('mardin', 'mazidagi', 'Mazıdağı'),
  ('mardin', 'midyat', 'Midyat'),
  ('mardin', 'nusaybin', 'Nusaybin'),
  ('mardin', 'omerli', 'Ömerli'),
  ('mardin', 'savur', 'Savur'),
  ('mersin', 'akdeniz', 'Akdeniz'),
  ('mersin', 'anamur', 'Anamur'),
  ('mersin', 'aydincik', 'Aydıncık'),
  ('mersin', 'bozyazi', 'Bozyazı'),
  ('mersin', 'camliyayla', 'Çamlıyayla'),
  ('mersin', 'erdemli', 'Erdemli'),
  ('mersin', 'gulnar', 'Gülnar'),
  ('mersin', 'mezitli', 'Mezitli'),
  ('mersin', 'mut', 'Mut'),
  ('mersin', 'silifke', 'Silifke'),
  ('mersin', 'tarsus', 'Tarsus'),
  ('mersin', 'toroslar', 'Toroslar'),
  ('mersin', 'yenisehir', 'Yenişehir'),
  ('mugla', 'bodrum', 'Bodrum'),
  ('mugla', 'dalaman', 'Dalaman'),
  ('mugla', 'datca', 'Datça'),
  ('mugla', 'fethiye', 'Fethiye'),
  ('mugla', 'kavaklidere', 'Kavaklıdere'),
  ('mugla', 'koycegiz', 'Köyceğiz'),
  ('mugla', 'marmaris', 'Marmaris'),
  ('mugla', 'mentese', 'Menteşe'),
  ('mugla', 'milas', 'Milas'),
  ('mugla', 'ortaca', 'Ortaca'),
  ('mugla', 'seydikemer', 'Seydikemer'),
  ('mugla', 'ula', 'Ula'),
  ('mugla', 'yatagan', 'Yatağan'),
  ('mus', 'merkez', 'Merkez'),
  ('mus', 'bulanik', 'Bulanık'),
  ('mus', 'haskoy', 'Hasköy'),
  ('mus', 'korkut', 'Korkut'),
  ('mus', 'malazgirt', 'Malazgirt'),
  ('mus', 'varto', 'Varto'),
  ('nevsehir', 'merkez', 'Merkez'),
  ('nevsehir', 'acigol', 'Acıgöl'),
  ('nevsehir', 'avanos', 'Avanos'),
  ('nevsehir', 'derinkuyu', 'Derinkuyu'),
  ('nevsehir', 'gulsehir', 'Gülşehir'),
  ('nevsehir', 'hacibektas', 'Hacıbektaş'),
  ('nevsehir', 'kozakli', 'Kozaklı'),
  ('nevsehir', 'urgup', 'Ürgüp'),
  ('nigde', 'merkez', 'Merkez'),
  ('nigde', 'altunhisar', 'Altunhisar'),
  ('nigde', 'bor', 'Bor'),
  ('nigde', 'camardi', 'Çamardı'),
  ('nigde', 'ciftlik', 'Çiftlik'),
  ('nigde', 'ulukisla', 'Ulukışla'),
  ('ordu', 'altinordu', 'Altınordu'),
  ('ordu', 'akkus', 'Akkuş'),
  ('ordu', 'aybasti', 'Aybastı'),
  ('ordu', 'camas', 'Çamaş'),
  ('ordu', 'catalpinar', 'Çatalpınar'),
  ('ordu', 'caybasi', 'Çaybaşı'),
  ('ordu', 'fatsa', 'Fatsa'),
  ('ordu', 'golkoy', 'Gölköy'),
  ('ordu', 'gulyali', 'Gülyalı'),
  ('ordu', 'gurgentepe', 'Gürgentepe'),
  ('ordu', 'ikizce', 'İkizce'),
  ('ordu', 'kabaduz', 'Kabadüz'),
  ('ordu', 'kabatas', 'Kabataş'),
  ('ordu', 'korgan', 'Korgan'),
  ('ordu', 'kumru', 'Kumru'),
  ('ordu', 'mesudiye', 'Mesudiye'),
  ('ordu', 'persembe', 'Perşembe'),
  ('ordu', 'ulubey', 'Ulubey'),
  ('ordu', 'unye', 'Ünye'),
  ('osmaniye', 'merkez', 'Merkez'),
  ('osmaniye', 'bahce', 'Bahçe'),
  ('osmaniye', 'duzici', 'Düziçi'),
  ('osmaniye', 'hasanbeyli', 'Hasanbeyli'),
  ('osmaniye', 'kadirli', 'Kadirli'),
  ('osmaniye', 'sumbas', 'Sumbas'),
  ('osmaniye', 'toprakkale', 'Toprakkale'),
  ('rize', 'merkez', 'Merkez'),
  ('rize', 'ardesen', 'Ardeşen'),
  ('rize', 'camlihemsin', 'Çamlıhemşin'),
  ('rize', 'cayeli', 'Çayeli'),
  ('rize', 'derepazari', 'Derepazarı'),
  ('rize', 'findikli', 'Fındıklı'),
  ('rize', 'guneysu', 'Güneysu'),
  ('rize', 'hemsin', 'Hemşin'),
  ('rize', 'ikizdere', 'İkizdere'),
  ('rize', 'iyidere', 'İyidere'),
  ('rize', 'kalkandere', 'Kalkandere'),
  ('rize', 'pazar', 'Pazar'),
  ('sakarya', 'adapazari', 'Adapazarı'),
  ('sakarya', 'akyazi', 'Akyazı'),
  ('sakarya', 'arifiye', 'Arifiye'),
  ('sakarya', 'erenler', 'Erenler'),
  ('sakarya', 'ferizli', 'Ferizli'),
  ('sakarya', 'geyve', 'Geyve'),
  ('sakarya', 'hendek', 'Hendek'),
  ('sakarya', 'karapurcek', 'Karapürçek'),
  ('sakarya', 'karasu', 'Karasu'),
  ('sakarya', 'kaynarca', 'Kaynarca'),
  ('sakarya', 'kocaali', 'Kocaali'),
  ('sakarya', 'mithatpasa', 'Mithatpaşa'),
  ('sakarya', 'pamukova', 'Pamukova'),
  ('sakarya', 'sapanca', 'Sapanca'),
  ('sakarya', 'serdivan', 'Serdivan'),
  ('sakarya', 'sogutlu', 'Söğütlü'),
  ('samsun', 'alacam', 'Alaçam'),
  ('samsun', 'asarcik', 'Asarcık'),
  ('samsun', 'atakum', 'Atakum'),
  ('samsun', 'ayvacik', 'Ayvacık'),
  ('samsun', 'bafra', 'Bafra'),
  ('samsun', 'canik', 'Canik'),
  ('samsun', 'carsamba', 'Çarşamba'),
  ('samsun', 'havza', 'Havza'),
  ('samsun', 'ilkadim', 'İlkadım'),
  ('samsun', 'kavak', 'Kavak'),
  ('samsun', 'ladik', 'Ladik'),
  ('samsun', 'ondokuzmayis', 'Ondokuzmayıs'),
  ('samsun', 'salipazari', 'Salıpazarı'),
  ('samsun', 'tekkekoy', 'Tekkeköy'),
  ('samsun', 'terme', 'Terme'),
  ('samsun', 'vezirkopru', 'Vezirköprü'),
  ('samsun', 'yakakent', 'Yakakent'),
  ('sanliurfa', 'akcakale', 'Akçakale'),
  ('sanliurfa', 'birecik', 'Birecik'),
  ('sanliurfa', 'bozova', 'Bozova'),
  ('sanliurfa', 'ceylanpinar', 'Ceylanpınar'),
  ('sanliurfa', 'eyyubiye', 'Eyyübiye'),
  ('sanliurfa', 'halfeti', 'Halfeti'),
  ('sanliurfa', 'haliliye', 'Haliliye'),
  ('sanliurfa', 'harran', 'Harran'),
  ('sanliurfa', 'hilvan', 'Hilvan'),
  ('sanliurfa', 'karakopru', 'Karaköprü'),
  ('sanliurfa', 'siverek', 'Siverek'),
  ('sanliurfa', 'suruc', 'Suruç'),
  ('sanliurfa', 'viransehir', 'Viranşehir'),
  ('siirt', 'merkez', 'Merkez'),
  ('siirt', 'baykan', 'Baykan'),
  ('siirt', 'eruh', 'Eruh'),
  ('siirt', 'kurtalan', 'Kurtalan'),
  ('siirt', 'pervari', 'Pervari'),
  ('siirt', 'sirvan', 'Şirvan'),
  ('siirt', 'tillo', 'Tillo'),
  ('sinop', 'merkez', 'Merkez'),
  ('sinop', 'ayancik', 'Ayancık'),
  ('sinop', 'boyabat', 'Boyabat'),
  ('sinop', 'dikmen', 'Dikmen'),
  ('sinop', 'duragan', 'Durağan'),
  ('sinop', 'erfelek', 'Erfelek'),
  ('sinop', 'gerze', 'Gerze'),
  ('sinop', 'sarayduzu', 'Saraydüzü'),
  ('sinop', 'turkeli', 'Türkeli'),
  ('sirnak', 'merkez', 'Merkez'),
  ('sirnak', 'beytussebap', 'Beytüşşebap'),
  ('sirnak', 'cizre', 'Cizre'),
  ('sirnak', 'guclukonak', 'Güçlükonak'),
  ('sirnak', 'idil', 'İdil'),
  ('sirnak', 'silopi', 'Silopi'),
  ('sirnak', 'uludere', 'Uludere'),
  ('sivas', 'merkez', 'Merkez'),
  ('sivas', 'akincilar', 'Akıncılar'),
  ('sivas', 'altinyayla', 'Altınyayla'),
  ('sivas', 'divrigi', 'Divriği'),
  ('sivas', 'dogansar', 'Doğanşar'),
  ('sivas', 'gemerek', 'Gemerek'),
  ('sivas', 'golova', 'Gölova'),
  ('sivas', 'hafik', 'Hafik'),
  ('sivas', 'imranli', 'İmranlı'),
  ('sivas', 'kangal', 'Kangal'),
  ('sivas', 'koyulhisar', 'Koyulhisar'),
  ('sivas', 'sarkisla', 'Şarkışla'),
  ('sivas', 'susehri', 'Suşehri'),
  ('sivas', 'ulas', 'Ulaş'),
  ('sivas', 'yildizeli', 'Yıldızeli'),
  ('sivas', 'zara', 'Zara'),
  ('tekirdag', 'cerkezkoy', 'Çerkezköy'),
  ('tekirdag', 'corlu', 'Çorlu'),
  ('tekirdag', 'ergene', 'Ergene'),
  ('tekirdag', 'hayrabolu', 'Hayrabolu'),
  ('tekirdag', 'kapakli', 'Kapaklı'),
  ('tekirdag', 'malkara', 'Malkara'),
  ('tekirdag', 'marmaraereglisi', 'Marmaraereğlisi'),
  ('tekirdag', 'muratli', 'Muratlı'),
  ('tekirdag', 'saray', 'Saray'),
  ('tekirdag', 'suleymanpasa', 'Süleymanpaşa'),
  ('tekirdag', 'sarkoy', 'Şarköy'),
  ('tokat', 'merkez', 'Merkez'),
  ('tokat', 'almus', 'Almus'),
  ('tokat', 'artova', 'Artova'),
  ('tokat', 'basciftlik', 'Başçiftlik'),
  ('tokat', 'erbaa', 'Erbaa'),
  ('tokat', 'niksar', 'Niksar'),
  ('tokat', 'pazar', 'Pazar'),
  ('tokat', 'resadiye', 'Reşadiye'),
  ('tokat', 'sulusaray', 'Sulusaray'),
  ('tokat', 'turhal', 'Turhal'),
  ('tokat', 'yesilyurt', 'Yeşilyurt'),
  ('tokat', 'zile', 'Zile'),
  ('trabzon', 'akcaabat', 'Akçaabat'),
  ('trabzon', 'arakli', 'Araklı'),
  ('trabzon', 'arsin', 'Arsin'),
  ('trabzon', 'besikduzu', 'Beşikdüzü'),
  ('trabzon', 'carsibasi', 'Çarşıbaşı'),
  ('trabzon', 'caykara', 'Çaykara'),
  ('trabzon', 'dernekpazari', 'Dernekpazarı'),
  ('trabzon', 'duzkoy', 'Düzköy'),
  ('trabzon', 'hayrat', 'Hayrat'),
  ('trabzon', 'koprubasi', 'Köprübaşı'),
  ('trabzon', 'macka', 'Maçka'),
  ('trabzon', 'of', 'Of'),
  ('trabzon', 'ortahisar', 'Ortahisar'),
  ('trabzon', 'salpazari', 'Şalpazarı'),
  ('trabzon', 'surmene', 'Sürmene'),
  ('trabzon', 'tonya', 'Tonya'),
  ('trabzon', 'vakfikebir', 'Vakfıkebir'),
  ('trabzon', 'yomra', 'Yomra'),
  ('tunceli', 'merkez', 'Merkez'),
  ('tunceli', 'cemisgazek', 'Çemişgezek'),
  ('tunceli', 'hozat', 'Hozat'),
  ('tunceli', 'mazgirt', 'Mazgirt'),
  ('tunceli', 'nazimiye', 'Nazımiye'),
  ('tunceli', 'ovacik', 'Ovacık'),
  ('tunceli', 'pertek', 'Pertek'),
  ('tunceli', 'pulumur', 'Pülümür'),
  ('usak', 'merkez', 'Merkez'),
  ('usak', 'banaz', 'Banaz'),
  ('usak', 'esme', 'Eşme'),
  ('usak', 'karahalli', 'Karahallı'),
  ('usak', 'sivasli', 'Sivaslı'),
  ('usak', 'ulubey', 'Ulubey'),
  ('van', 'edremit', 'Edremit'),
  ('van', 'ercis', 'Erciş'),
  ('van', 'bahcesaray', 'Bahçesaray'),
  ('van', 'baskale', 'Başkale'),
  ('van', 'caldiran', 'Çaldıran'),
  ('van', 'catak', 'Çatak'),
  ('van', 'gevas', 'Gevaş'),
  ('van', 'gurpinar', 'Gürpınar'),
  ('van', 'ipekyolu', 'İpekyolu'),
  ('van', 'muradiye', 'Muradiye'),
  ('van', 'ozalp', 'Özalp'),
  ('van', 'saray', 'Saray'),
  ('van', 'tusba', 'Tuşba'),
  ('yalova', 'merkez', 'Merkez'),
  ('yalova', 'altinova', 'Altınova'),
  ('yalova', 'armutlu', 'Armutlu'),
  ('yalova', 'ciftlikkoy', 'Çiftlikköy'),
  ('yalova', 'cinarcik', 'Çınarcık'),
  ('yalova', 'termal', 'Termal'),
  ('yozgat', 'merkez', 'Merkez'),
  ('yozgat', 'akdagmadeni', 'Akdağmadeni'),
  ('yozgat', 'aydincik', 'Aydıncık'),
  ('yozgat', 'bogazliyan', 'Boğazlıyan'),
  ('yozgat', 'candir', 'Çandır'),
  ('yozgat', 'cayiralan', 'Çayıralan'),
  ('yozgat', 'cekerek', 'Çekerek'),
  ('yozgat', 'kadisehri', 'Kadışehri'),
  ('yozgat', 'saraykent', 'Saraykent'),
  ('yozgat', 'sarikaya', 'Sarıkaya'),
  ('yozgat', 'sorgun', 'Sorgun'),
  ('yozgat', 'sefaatli', 'Şefaatli'),
  ('yozgat', 'ulukoy', 'Uluköy'),
  ('yozgat', 'yerkoy', 'Yerköy'),
  ('zonguldak', 'merkez', 'Merkez'),
  ('zonguldak', 'alapli', 'Alaplı'),
  ('zonguldak', 'caycuma', 'Çaycuma'),
  ('zonguldak', 'devrek', 'Devrek'),
  ('zonguldak', 'eregli', 'Ereğli'),
  ('zonguldak', 'gokcebey', 'Gökçebey'),
  ('zonguldak', 'kilimli', 'Kilimli');

UPDATE regions r
SET name = src.name
FROM _tr_region_names src
JOIN countries c ON lower(trim(c.iso2)) = 'tr'
WHERE r.country_id = c.id
  AND r.slug = src.slug
  AND r.name IS DISTINCT FROM src.name;

UPDATE districts d
SET name = src.name
FROM _tr_district_names src
JOIN regions r ON r.slug = src.region_slug
JOIN countries c ON c.id = r.country_id AND lower(trim(c.iso2)) = 'tr'
WHERE d.region_id = r.id
  AND d.slug = src.slug
  AND d.name IS DISTINCT FROM src.name;

UPDATE location_pages lp
SET
  title = r.name,
  translations_json = jsonb_set(coalesce(lp.translations_json, '{}'::jsonb), '{tr,name}', to_jsonb(r.name), true),
  updated_at = now()
FROM regions r
JOIN countries c ON c.id = r.country_id AND lower(trim(c.iso2)) = 'tr'
WHERE lp.region_id = r.id
  AND coalesce(lp.region_type, 'province') = 'province'
  AND (lp.title IS DISTINCT FROM r.name OR coalesce(lp.translations_json->'tr'->>'name', '') IS DISTINCT FROM r.name);

UPDATE location_pages lp
SET
  title = d.name,
  translations_json = jsonb_set(coalesce(lp.translations_json, '{}'::jsonb), '{tr,name}', to_jsonb(d.name), true),
  updated_at = now()
FROM districts d
JOIN regions r ON r.id = d.region_id
JOIN countries c ON c.id = r.country_id AND lower(trim(c.iso2)) = 'tr'
WHERE lp.district_id = d.id
  AND coalesce(lp.region_type, 'district') = 'district'
  AND (lp.title IS DISTINCT FROM d.name OR coalesce(lp.translations_json->'tr'->>'name', '') IS DISTINCT FROM d.name);

COMMIT;
