/** Villa ilan formu (`VerticalDetailsSection`) çipleri — `theme_codes` ile aynı kodlar */
export const VILLA_THEME_CHIP_PRESETS: { code: string; label: string }[] = [
  { code: 'pool', label: 'Özel Havuz' },
  { code: 'sea_view', label: 'Deniz Manzarası' },
  { code: 'mountain_view', label: 'Dağ Manzarası' },
  { code: 'beachfront', label: 'Sahilde / denize sıfır' },
  { code: 'conservative', label: 'Muhafazakar' },
  { code: 'garden', label: 'Bahçeli' },
  { code: 'jacuzzi', label: 'Jakuzi' },
  { code: 'sauna', label: 'Sauna' },
  { code: 'bbq', label: 'Barbekü' },
  { code: 'fireplace', label: 'Şömine' },
  { code: 'pet_friendly', label: 'Evcil Hayvan Kabul' },
  { code: 'child_friendly', label: 'Çocuk Dostu' },
  { code: 'wheelchair', label: 'Engelli Erişim' },
  { code: 'wifi', label: 'Wi-Fi' },
  { code: 'ac', label: 'Klima' },
  { code: 'parking', label: 'Ücretsiz Otopark' },
  { code: 'dishwasher', label: 'Bulaşık Makinesi' },
  { code: 'washing_machine', label: 'Çamaşır Makinesi' },
  { code: 'tv', label: 'TV' },
  { code: 'gym', label: 'Fitness Salonu' },
  { code: 'tennis', label: 'Tenis Kortu' },
]
